### PR TITLE
Consider removing UnnecessaryAsyncFixer and UnnecessaryAsyncAnalyzer

### PR DESCRIPTION
**Pull request by tjrobinson**
Given this recent advice from @davidfowl at Microsoft, the `UnnecessaryAsync` analyzer and fixer should probably be removed?

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task

I couldn't raise an issue so created a quick PR instead. I can't test it as the `RosylnUtilities` project isn't committed to GitHub.

Thanks.

### CODE REVIEW

**Comment by Eli-Black-Work** [comment]
Agreed :)  I usually silence this class of warning soon after installing the analyzer.

**Comment by davidfowl** [comment]
Does this analyzer detect the buggy cases (wrapped in a using etc?). I don't think you need to follow my advance to the tee for this one mostly because if you *are* doing something performance sensitive, I can understand wanting to have an analyzer like this but I wouldn't have it on by default.

**Comment by JimBobSquarePants** [comment]
The analyzer will correctly not raise the warning when a using statement is wrapping the awaitable task but will incorrectly raise it when a using declaration is used. 

Perhaps the analyzers detection should be reversed and it should look for non-await use in disposable patterns only?

**Comment by semihokur** [comment]
I found this repo from google and it was probably created by a bot based on an old version. I recently re-opensourced AsyncFixer here: https://github.com/semihokur/asyncfixer

Regarding 'Unnecessary async' analyzer, we find it very useful in many Microsoft projects including [BuildXL](https://github.com/microsoft/buildxl). We saw significant performance improvements (both memory and time) when removing unnecessary async/await keywords in hot paths. Even though I agree with David's points in his guidance article, AsyncFixer's goal is to find performance issues related to async/await. 

AsyncFixer does not suggest removing await expressions involving disposable objects created via (i) `using` blocks or (ii) `using` statements. We also have another analyzer, *AsyncFixer04: AsyncCallInsideUsingBlock* to detect leaking tasks inside using blocks, so that we can prevent `ObjectDisposedException`.

**Comment by Eli-Black-Work** [comment]
Thanks for letting us know, @semihokur!

@modulexcite, Would you be okay with adding a note to this repo's README that points to the new official asyncfixer repo?

**Pull request closed without merging**
